services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: mj_on_rails/web:latest
    container_name: mj_on_rails_web
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - ".:/app"
      - gem_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
    stdin_open: true
    tty: true

volumes:
  gem_cache:
