name: CI

on:
  push:
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: docker compose up
        run: docker compose up -d

      - name: Run RSpec
        run: docker compose exec -T web bundle exec rspec

  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: docker compose up
        run: docker compose up -d

      - name: Run Rubocop
        run: docker compose exec -T web bundle exec rubocop -D -E -S -P
